#!/usr/bin/bash
#Tools SadapWhatsApp
#Sadap WhatsApp
#By User C 
#Jangan DiRecord Tod!!!
#Bersihkan Layar
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
echo " "
echo  $blue "<|======================================|>"
echo  $blue "<|            Tools SadapWhatsApp       |>"
echo  $blue "<|                                      |>"
echo  $blue "<| Name: R13F_HKR  ||     Rifqi ikhsan  |>"
echo  $blue "<| MyTeam: SMPN 1 jalan agak            |>"
echo  $blue "<| Contact: 089629814773                |>"
echo  $blue "<| Thanks To: apay, Carlos, Hanna, fariz|>"
echo  $blue "<|======================================|>"
sleep 1
echo  $red "============== $red MENU $green ================="
echo $blue "================================================="
echo $blue "|| $green 1. Sadap WhatsApp No Indosat   $blue ||"
echo $blue "|| $green 2. Sadap WhatsApp No Telkomsel $blue ||"
echo $blue "|| $green 3. Sadap WhatsApp No XL / Axis $blue ||"
echo $blue "|| $green 4. Sadap WhatsApp No 3(Three)  $blue ||"
echo $blue "|| $green 0. Exit Sadap WhatsApp         $blue ||"
echo $blue "================================================="
echo $blue"╭──[Masukkan Pilihan Anda]>"
read -p"╰───────root@User C=•>"bro;
if [ $bro C = 1 ] || [ $bro C = 1 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@User C=•>"bro;
sleep 2
echo $red "[+]Scaning...."
sleep 3
echo $blue "10%"
sleep 4
echo $green "20%"
sleep 2
echo $cyan "30%"
sleep 8
echo $purple "40%"
sleep 3
echo $blue "50%"
sleep 2
echo $red "60%"
sleep 5
echo $green "70%"
sleep 6
echo $cyan "80%"
sleep 7
echo $purple "90%"
sleep 3
echo $blue "100%"
sleep 2
echo $green "Prosessing Done"
sleep 4
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Verifikasi"fi
fi

if [ $bro = 2 ] || [ $bro = 2 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@User C=•>"bro;
sleep 2
echo $red "[+]Scaning...."
sleep 5
echo $blue "10%"
sleep 3
echo $green "20%"
sleep 8
echo $cyan "30%"
sleep 3
echo $purple "40%"
sleep 6
echo $blue "50%"
sleep 5
echo $red "60%"
sleep 4
echo $green "70%"
sleep 6
echo $cyan "80%"
sleep 8
echo $purple "90%"
sleep 6
echo $blue "100%"
sleep 9
echo $green "Prosessing Done"
sleep 3
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Verifikasi"
fi

if [ $bro = 3 ] || [ $bro = 3 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@user C=•>"bro;
sleep 2
echo $red "[+]Scaning...."
sleep 8
echo $blue "10%"
sleep 4
echo $green "20%"
sleep 5
echo $cyan "30%"
sleep 6
echo $purple "40%"
sleep 4
echo $blue "50%"
sleep 2
echo $red "60%"
sleep 3
echo $green "70%"
sleep 9
echo $cyan "80%"
sleep 7
echo $purple "90%"
sleep 4
echo $blue "100%"
sleep 9
echo $green "Prosessing Done"
sleep 9
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Nomer $Kode Verifikasi"
fi

if [ $bro = 4 ] || [ $bro = 4 ]
then
echo $blue"╭──[Silahkan Masukan Nomernya]>"
read -p"╰───────root@User C=•>"bro;
sleep 2
echo $red "[+]Scaning...."
sleep 8
echo $blue "10%"
sleep 7
echo $green "20%"
sleep 5
echo $cyan "30%"
sleep 4
echo $purple "40%"
sleep 5.5
echo $blue "50%"
sleep 4
echo $red "60%"
sleep 5
echo $green "70%"
sleep 6
echo $cyan "80%"
sleep 7
echo $purple "90%"
sleep 5
echo $blue "100%"
sleep 3
echo $green "Prosessing Done"
sleep 4
echo  $blue "Nomer WhatsApp Berhasil Di Sadap $Nomer $Kode Verifikasi"
fi

if [ $bro = 0 ] || [ $bro = 0 ]
then
echo  $red "Bye Bye stahh ku"
echo  $blue "Jangan Lupa subscribe newbie tutorial Kalo Bisa!"
echo  $green "User C!"
exit
fi
